version: '3.5'


services:
  postgres:
    container_name: movieShopDatabase
    image: postgres:13.1
    env_file:
      - database.env
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data:
