spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movieShopDb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: true
        SQL: DEBUG
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db-changelog-master.xml